services:
  database:
    image: postgres
    container_name: db_ignite_node_rentx
    restart: always
    ports:
      - 65432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=b3R6RGHjsdvLnP
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/

  redis:
    image: redis:alpine
    ports:
      - 26379:6379

  

volumes:
  pgdata:
    driver: local