services:
  database:
    image: postgres
    container_name: db_ignite_node_rentx
    restart: always
    ports:
      - 65432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=b3R&6RGH%jsdvLnP
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/

volumes:
  pgdata:
    driver: local